### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by caijie12138** [microsoft/NeuronBlocks#19]
when I run python train.py --conf_path=model_zoo/demo/conf.json . An Error occurs, anyone meet this error:
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    main(params)
  File "train.py", line 227, in main
    lm.train(optimizer, loss_fn)
  File "~/NeuronBlocks-master/LearningMachine.py", line 156, in train
    logits_softmax = self.model(inputs_desc, length_desc, *param_list)
  File "~/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "~/NeuronBlocks-master/Model.py", line 357, in forward
    inputs, lengths = transform_tensors2params(inputs_desc, length_desc, param_list)
  File "~/NeuronBlocks-master/utils/common_utils.py", line 176, in transform_tensors2params
    lengths[key] = param_list[length_desc[key]]
IndexError: tuple index out of range

**Comment by ljshou** [comment]
Hi caijie，found that you are using python 3.5. currently we support Python 3.6. we are trying to the issue you met.

**Comment by adolphk-yk** [comment]
Hi caijie, this issue is caused by python 3.5.x, you can update python to 3.6.x .

**Comment by caijie12138** [comment]
Thank you!
