### ISSUE TITLE
install issue - ERROR: scipy 1.7.1 has requirement numpy<1.23.0,>=1.16.5, but you'll have numpy 1.16.3 which is incompatible.

### ISSUE THREAD

**Issue by TomaszMyszak** [microsoft/NeuronBlocks#87]
Hi, 
when I trying install this app I have in Zorin OS issue: 
"ERROR: scipy 1.7.1 has requirement numpy<1.23.0,>=1.16.5, but you'll have numpy 1.16.3 which is incompatible."

Is this important?

**Comment by TomaszMyszak** [comment]
and other issue when I try to run autotest.sh:

Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from settings import ProblemTypes, version, Setting as st
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from settings import ProblemTypes, version
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from settings import ProblemTypes, version, Setting as st
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from settings import ProblemTypes, version
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from settings import ProblemTypes, version, Setting as st
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from settings import ProblemTypes, version
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from settings import ProblemTypes, version, Setting as st
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from settings import ProblemTypes, version
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/settings.py", line 61
    class ConstantStatic(metaclass=Constant):
                                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "./autotest/tools/get_results.py", line 2, in <module>
    from calculate_AUC import main
  File "/home/tomek/AI/NeutronBlocks/NeuronBlocks/autotest/tools/calculate_AUC.py", line 5, in <module>
    from sklearn.metrics import roc_auc_score
ImportError: No module named sklearn.metrics
